title: Khang Chung # your name (or website title) here
logo: "images/IMG_8262.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://github.com/khang-chung">View My Github Profile</a> 
  
# theme: jekyll-theme-minimal
theme: jekyll-theme-midnight
google_analytics: UA-142468239-1 # your Google Analytics tracking ID here
